### ISSUE TITLE
parsing fails

### ISSUE THREAD

**Issue by abhishek-gamooga** [harrisiirak/cron-parser#110]
const cron = require('cron-parser');
cron.parseExpression('15 10 * 9 *').next().toString();

throws: 
Error: Invalid explicit day of month definition
    at CronExpression._findSchedule (/somepath/Desktop/ww-api/ww-apis/node_modules/cron-parser/lib/expression.js:444:15)
    at CronExpression.next (/somepath/Desktop/ww-api/ww-apis/node_modules/cron-parser/lib/expression.js:537:23)
    at repl:1:44
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:279:10)
    at REPLServer.Interface._line (readline.js:626:8)
    at REPLServer.Interface._ttyWrite (readline.js:906:14)
    at REPLServer.self._ttyWrite (repl.js:509:7)
    at ReadStream.onkeypress (readline.js:158:10)
    at emitTwo (events.js:125:13)
    at ReadStream.emit (events.js:213:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1007:36)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)

**Comment by harrisiirak** [comment]
Related to this part of the code: https://github.com/harrisiirak/cron-parser/blob/master/lib/expression.js#L443

Need to think what is the best fix/workaround for this issue.

Thanks for reporting!

**Comment by abhishek-gamooga** [comment]
@harrisiirak Thanks for acting so fast on it :+1:
