### ISSUE TITLE
Does not support '?'

### ISSUE THREAD

**Issue by fir3pho3nixx** [harrisiirak/cron-parser#21]
Do you think it would be possible to add support for '?'. This lib has saved me heaps of time thanks for building it :)

Error: Invalid characters, got value: ?
    at Function._parseField (/usr/local/src/nodejs/voodoo/services/core/node_modules/cron-parser/lib/expression.js:129:11)
    at parse (/usr/local/src/nodejs/voodoo/services/core/node_modules/cron-parser/lib/expression.js:566:36)
    at Function.parse (/usr/local/src/nodejs/voodoo/services/core/node_modules/cron-parser/lib/expression.js:586:12)
    at Function.parseExpression (/usr/local/src/nodejs/voodoo/services/core/node_modules/cron-parser/lib/parser.js:39:25)

**Comment by fir3pho3nixx** [comment]
Old issue closing if that is OK. Thanks.

**Comment by fir3pho3nixx** [comment]
@harrisiirak - this is issue is 3 years old. I am try to get these off my issue tracking. Any chance of creating a new one?
