### ISSUE TITLE
Does not support 'L'?

### ISSUE THREAD

**Issue by fir3pho3nixx** [harrisiirak/cron-parser#22]
Again thanks for building this. This would make it better :)

Error: Invalid characters, got value: L
    at Function._parseField (/usr/local/src/nodejs/voodoo/services/core/node_modules/cron-parser/lib/expression.js:129:11)
    at parse (/usr/local/src/nodejs/voodoo/services/core/node_modules/cron-parser/lib/expression.js:566:36)
    at Function.parse (/usr/local/src/nodejs/voodoo/services/core/node_modules/cron-parser/lib/expression.js:586:12)
    at Function.parseExpression (/usr/local/src/nodejs/voodoo/services/core/node_modules/cron-parser/lib/parser.js:39:25)

**Comment by djmitche** [comment]
What does this mean?  What would "L" do?

**Comment by djmitche** [comment]
Ah, there's more context in #21 - https://en.wikipedia.org/wiki/Cron#Non-Standard_Characters

L would be "last" so "5L" would mean the last friday.

**Comment by fir3pho3nixx** [comment]
Old issue hope it is OK if I close. Clearing things out. Thanks!

**Comment by fir3pho3nixx** [comment]
Sorry @harrisiirak, will leave open.
