### ISSUE TITLE
some time zone names are not handled, but could be with luxon v 2.4.0

### ISSUE THREAD

**Issue by DonBrinn** [harrisiirak/cron-parser#271]
Steps to reproduce:

With cron-parser@4.4.0, which uses Luxon@1.28.0, run these commands:
```
> const cronParser = require('cron-parser');
> cronParser.parseExpression('0 0 5 * * *', {tz: 'EST5EDT', currentDate: new Date('2022-01-01T00:00:00.000Z'), endDate: new Date('2022-06-01T00:00:00.000Z')}).next().toDate();
```
Result:
```
Uncaught Error: CronDate: unhandled timestamp: "2022-01-01T00:00:00.000Z"
    at new CronDate (C:\github\brightspace\bds-generator\node_modules\cron-parser\lib\date.js:244:11)
    at new CronExpression (C:\github\brightspace\bds-generator\node_modules\cron-parser\lib\expression.js:29:23)
    at parse (C:\github\brightspace\bds-generator\node_modules\cron-parser\lib\expression.js:883:12)
    at Function.parse (C:\github\brightspace\bds-generator\node_modules\cron-parser\lib\expression.js:919:10)
    at Function.parseExpression (C:\github\brightspace\bds-generator\node_modules\cron-parser\lib\parser.js:41:25)
```

It seems that simply upgrading to use Luxon version 2.4.0 would fix this.  Locally, if I force cron-parser to use Luxon@2.4.0, then running the same command as above successfully results in the following output rather than the error:
```
2022-01-01T13:00:00.000Z
```

**Comment by harrisiirak** [comment]
Closed by #272
