### ISSUE TITLE
not support `1W` 

### ISSUE THREAD

**Issue by rashagu** [harrisiirak/cron-parser#274]
cron-parser@4.5.0

4 1/2 5 1W 1 ?
```
expression.js:177 
        
       Uncaught Error: Invalid characters, got value: 1W
    at Function._parseField (expression.js:177:11)
    at parse2 (expression.js:866:36)
    at Function.parse (expression.js:919:10)
    at Function.parseExpression (parser.js:41:25)
    at calTriggerListInner (index.tsx:161:29)
    at index.tsx:141:5
    at invokeFunc (lodash.js:10401:23)
    at trailingEdge (lodash.js:10450:18)
    at timerExpired (lodash.js:10438:18)
```

**Comment by harrisiirak** [comment]
Hi @rashagu ,

Please see supported format: https://github.com/harrisiirak/cron-parser#supported-format
