### ISSUE TITLE
Invalid explicit day of month definition

### ISSUE THREAD

**Issue by zxbin2000** [harrisiirak/cron-parser#52]
0 47 22 * * 3

[ERROR] error - Caught exception: Error: Invalid explicit day of month definition
    at CronExpression._findSchedule (/Users/***/dev/analy-engine/node_modules/cron-parser/lib/expression.js:388:15)
    at CronExpression.next (/Users/***/dev/analy-engine/node_modules/cron-parser/lib/expression.js:455:23)
    at scheduleNextRecurrence (/Users/***/dev/analy-engine/node_modules/node-schedule/lib/schedule.js:449:90)
    at null._onTimeout (/Users/***/dev/analy-engine/node_modules/node-schedule/lib/schedule.js:408:19)
    at Timer.listOnTimeout (timers.js:92:15)

3q~

**Comment by dimfeld** [comment]
Looks like this was fixed in 0.6.3, though I'm not 100% sure. In the latest code on npm, that exception is thrown from line 408, not 388, so updating the package may help.

**Comment by harrisiirak** [comment]
Latest published version is actually 1.1.0 (0.6.3 is quite old). Can't reproduce this issue. Provided pattern iterates as expected (I'm using the latest version).

**Comment by zxbin2000** [comment]
Thanks~
