### ISSUE TITLE
Issue on interval.getNext()

### ISSUE THREAD

**Issue by ssolbak** [harrisiirak/cron-parser#54]
var interval = CronParser.parseExpression('* 2 * * *', {currentDate: new Date('2016-02-08T21:49:22.527Z')});
console.log(interval.next());

I get the error "Invalid explicit day of month definition"

**Comment by devilj** [comment]
same here. here's my test:
```
$ cat test.cron.js 
var parser = require('cron-parser');

try {
  var interval = parser.parseExpression('*/2 * * * *');

  console.log('Date: ', interval.next().toString()); // Sat Dec 29 2012 00:42:00 GMT+0200 (EET)
  console.log('Date: ', interval.next().toString()); // Sat Dec 29 2012 00:44:00 GMT+0200 (EET)
  console.log('Date: ', interval.next().toUTC().toString()); // Sat Dec 28 2012 22:46:00 GMT+0200 (EET)
} catch (err) {
  console.error(err.stack);
  console.log('Error: ' + err.message);
}
$ node test.cron.js 
Error: Invalid explicit day of month definition
    at CronExpression._findSchedule (/home/ilj/_play_/netflow/node_modules/cron-parser/lib/expression.js:388:15)
    at CronExpression.next (/home/ilj/_play_/netflow/node_modules/cron-parser/lib/expression.js:455:23)
    at Object.<anonymous> (/home/ilj/_play_/netflow/test.cron.js:6:34)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:117:18)
    at node.js:948:3
Error: Invalid explicit day of month definition
```

i briefly looked into the code and it seems to me like the issue is in logic to handle Feb 29 on leap years.

**Comment by harrisiirak** [comment]
@ssolbak, @devilj - sure that your input string is correctly formatted and doesn't contain tab characters. @devilj tried your example and I'm not getting the error.

**Comment by harrisiirak** [comment]
And @devilj are you sure that you're using the latest version (1.1.0) of this library, because line numbers in your provided stacktrace doesn't match with the latest version.

**Comment by devilj** [comment]
@harrisiirak, yes, updating to 1.1 helps for this test case.
